version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis:6379
  worker:
    build: .
    environment:
      - REDIS_ADDRESS=redis:6379
  worker2:
    build: .
    environment:
      - REDIS_ADDRESS=redis:6379
  redis:
    image: "redis:5"